remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

# Setup
title:  "Maria's Demo Site"             
tagline:             
description:         
url:     http://eng470-s23.github.io          
baseurl:   /marias_demosite/            
